export const Traduction = Object.freeze({
   MODAL: Symbol("modal"),
   NAVBAR: Symbol("navbar"),
   LOADER: Symbol("loader"),
   TRANSACTION_TYPE: Symbol("transaction-type"),
   LOGIN: Symbol("login"),
   ACCOUNT_PAGE: Symbol("account"),
   AUTOMATION_PAGE: Symbol("automation"),
   AUTOMATIONS_PAGE: Symbol("automations"),
   UPDATE_AUTOMATION_PAGE: Symbol("update-automation"),
   HOME_PAGE: Symbol("home"),
   SIGN_IN_PAGE: Symbol("signIn"),
   TRANSACTION_PAGE: Symbol("transaction"),
   TRANSACTIONS_PAGE: Symbol("transactions"),
});