name: Register container and deploy

on:
   push:
      paths: [backend/**, .github/workflows/backend_workflow.yml, '!**.md', '!**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   test__build__and__push__image:
      runs-on: ubuntu-22.04
      permissions:
         contents: write
      defaults:
         run:
            working-directory: backend
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: backend
            fetch-depth: 0
         - uses: actions/setup-java@v4
           with:
            distribution: 'temurin'
            java-version: '17'
         - name: Initialize test
           run: ./gradlew clean test
         - name: Build and push image
           run: ./gradlew bootBuildImage -PDOCKER_PASS="${{ secrets.DOCKER_PASS }}" -PDOCKER_TAG=$(git rev-parse --short ${{ github.sha }})

   deploy__to_ecs:
      needs: [test__build__and__push__image]
      runs-on: ubuntu-22.04
      permissions:
         id-token: write
         contents: read
      steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-region: us-west-2
         role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Download task definition
        run: |
         aws ecs describe-task-definition --task-definition bank-account-service --query taskDefinition > taskdefinition.json
      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
         task-definition: task-definition.json
         container-name: web
         image: diegoj4v/bank-backend:$(git rev-parse --short ${{ github.sha }})
      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
         task-definition: ${{ steps.render-web-container.outputs.task-definition }}
         service: bank-api
         cluster: bank-cluster